
  SKBDClassic='Классическая';
  SKBDBrief='Сокращенная';
  SKBDEpsilon='Эпсилон';
  SKBDVisualStudio='Visual Studio';

  SVerbActionListEditor ='Редактор списка действий...';
  SVerbStandardAction = 'Новое стандартное действие...';


// ------------------- New Object captions -----------------

  SErrAlreadyInNewDialog='%s уже зарегистрирован для диалога "Новый Объект"';

  SDelphiApp='Delphi приложение';
  SVBScriptApp='VBScript приложение';
  SJScriptApp='JScript приложение';
  SPerlApp = 'Perl приложение';
  SPythonApp = 'Python приложение';

  SDelphiForm='Delphi форма';
  SVBScriptForm='VBScript форма';
  SJScriptForm='JScript форма';
  SPerlForm = 'Perl форма';
  SPythonForm = 'Python форма';

  SDelphiDataModule='Delphi модуль данных';
  SVBScriptDataModule='VBScript модуль данных';
  SJScriptDataModule='JScript модуль данных';
  SPerlDataModule='Perl модуль данных';
  SPythonDataModule='Python модуль данных';

  STextFile='Текстовый файл';
  SHTMLtext = 'HTML файл';
  SSqltext = 'SQL файл';

  SDelphiUnit='Delphi модуль';
  SJScriptUnit='JScript модуль';
  SVBScriptUnit='VBScript модуль';
  SPerlUnit='Perl модуль';
  SPythonUnit='Python модуль';

  SDelphiReport='Delphi отчет';
  SPerlReport='Perl отчет';
  SVBScriptReport='VBScript отчет';
  SJScriptReport='JScript отчет';
  SSimpleReport='Простой отчет';
  SPythonReport='Python отчет';

  SSimpleForm='Простая форма';
  SSimpleDataModule='Простой модуль данных';

  SProjectFile='Проект';
  SWorkSpaceFile='Рабочая область';


//--------------------- File Types captions --------------


  SAllFiles='Все файлы';
  SUnitFiles='Модули';
  SProjectWorkSpace='Проекты/Рабочие области';
  SFormFile='Формы';

//--------------------- Verb captions --------------

  SVerbMenuItems = 'Редактировать &Элементы...';
  SVerbSave='&Сохранить';
  SVerbSaveAs='Сохранить &как...';
  SVerbClose='&Закрыть';
  SVerbActivateProject='Активировать проект';
  SVerbAdd='&Добавить...';
  SVerbSQLEditor ='Редактор SQL...';
  SVerbResourceMaster = 'Мастер ресурсов';
  SVerbIdeInspector  ='IDE инспектор';
  SVerbMultiSourceEditor = 'Редактировать источники данных...';

  SRegPackages='Библиотеки';

//--------------------- Dialog titles --------------

  SExportToTitle = 'Экспорт в';
  SSaveAsTitle = 'Сохранить как';
  SOpenTitle = 'Открыть';


//--------------------- Parser Errors ----------------------------

  SErrCharPos=' Строка:%d, Столбец:%d. ';
  SErrMaxIfDefReached='Разрешено только %d вложенных уровней директив компилятора';
  SErrCompilerDirective='Неправильная директива компилятора: "%s"';
  STokenListEmpty='Список токенов пуст';
  SErrFutureState='Состояние в будущем';
  SErrTokenExpected='Ожидается %d';

// -------------------- Other Errors -------------------------

  SErrFormNameEmpty='Имя формы не может быть пустым';
  SErrMethodReferenced='Метод  %s не существуeт. Удалить ссылку?';
  SErrControlsInData = 'Визуальная компонента не может быть добавлена в модуль данных';
  SErrInvalidModuleClass = 'Неправильный класс модуля - %s';
  SErrCreatingForm='Ошибка при создании формы';
  SErrUpdateRes = 'Ошибка при обновлении ресурса';
  SErrOnlyForms='Эта версия Мастера Ресурсов позволяет редактировать только формы';
  SErrAlreadyInProject='Объект с именем "%s" уже находится в проекте';
  SErrOnlyWin32FileSystem='Эта операция может быть выполнена только на Win32 файловой системе';
  SErrObjectNotInProject='Объект %S не найден в активном проекте';
  SErrNotInstantReport='Может быть добавлен только в TInstantReport';
  SErrAlreadyUseAll='Объект %S уже использует все доступные формы';
  SErrBadPropStream='Ошибка в потоке свойств';
  SErrNoComp='Компонента %s не существует';
  SErrAlreadyHaveOwner='У этой рабочей области уже есть владелец';
  SErrNonMonoSpacedFont = 'Могут быть использованы только моноширинные шрифты';
  SerrInvalidMoving = 'Перемещение невозможно';
  sErrCantOpen= 'Нельзя открыть модуль %s'#13#10'Код ошибки : %d';
  SErrNoNewExtensions = 'Расширение диалога Новый Объект не установлено';
  SErrOpenFile = 'Ошибка открытия %s';
  SErrorCreateMap  = 'Ошибка создания file mapping';
  SErrorMap    = 'Нельзя отобразить %s на память';
  SErrReadOnlyFile='''%s'' является файлом только для чтения';
//------------------Scripter constants ----------------------------------

  SErrScriptEngineRun = 'Скрипт не может быть запущен';
  SErrAlreadyLaunched = 'Программа уже запущена';
  SErrNoCodeDesigner  = 'Ни одного дизайнера кода не зарегистрировано для %s типа файла';
  SErrNoScriptRunner  = 'Ни одного обработчика скрипта не зарегистрировано для %s типа файла';
  SErrNoScriptForLang = 'Ни одного обработчика скрипта не зарегистрировано для %s языка';
  SErrUnitNotFound    = 'Невозможно загрузить модуль %s';
  SErrNoRunnableObjects = 'Запуск невозможен';
  SErrExternalRun     = 'Ошибка при запуске программы : %s';
  SContinueExecution  = 'Продолжить выполнение?';
  SFilePrefix = 'Файл : ';

//----------------------------------------------------

  SOtherGroupName='Другие'; // in Object Inspector
  STitleFilterName='Имя фильтра';
  STitleFilter='Фильтр';
  SVerbUsesRetriever = 'Классификатор модулей...';
  SVerbAssignVerbs='Назначить действия';
  SCapUseObjects='Использовать объекты в ';
  SCapRunParameters='Параметры запуска';

  SPageNew='Новый';
  SPageForm='Форма';
  SPageUnit='Модуль';
  SPageReport='Отчет';
  SPageDataModule='Модуль данных';


  SWorkSpace='Рабочая область';
  SProject='Проект';

  SErrCantSaveObject='Невозможно сохранить объект';
  SErrDeleteFile='Невозможно удалить файл %S';
  SErrRenameFile='Нельзя переименовать файл %s в файл %s';
  SErrCantCreateTemp='Невозможно создать временное имя файла';

  SStatModified='Изменен';
  SStatInsert='Вставка';
  SStatOverwrite='Замена';
  SStatReadOnly ='Только для чтения';

  SErrOpenForm='Ошибка открытия формы';
  SErrDuplicateItem='Нельзя вставить элемент - дубликат';
  SErrReadProps = 'Ошибка при чтении свойств';

  SClipboard='Буфер обмена';


// OCX
  SErrOCXLoadFail = 'Ошибка при загрузке "%s"';
  SErrOCXCantFindProc = '%s процедура не найдена в "%s"';
  SErrOCXRegFail = 'Вызов  %s ошибочен в "%s"';


// ----------------- Filters ------------------------
  SOCXFilter = 'ActiveX (*.ocx)|*.ocx';
  SAVIFilesFilter = 'AVI файлы (*.avi)|*.avi';
{$IFDEF CPB3}
  SPackagesFilter='Библиотеки (*.bpl)|*.bpl';
{$ELSE}
  SPackagesFilter='Библиотеки (*.dpl)|*.dpl';
{$ENDIF}
  SPictFilter = 'Все файлы (*.jpg;*.jpeg;*.bmp;*.ico;*.emf;*.wmf)'+
    '|*.jpg;*.jpeg;*.bmp;*.ico;*.emf;*.wmf|JPEG Image File (*.jpg;*.jpeg)|*.jpg;*.jpeg|'+
    '|Bitmaps (*.bmp)|*.bmp|Icons (*.ico)|*.ico|'+
    'Enhanced Metafiles (*.emf)|*.emf|Metafiles (*.wmf)|*.wmf';
  SFormFilter='Дельфи - формы|*.dfm';
  SColorStyleFilter='Схемы цветов|*.RGB';

  SExeFilter= 'Исполняемые файлы|*.EXE;*.DLL;*.DPL;*.BPL|All Files|*.*';

  SExecutableFiles='Исполняемые файлы';

// ---------------- Palette Pages ---------------------

  SPalStandard='Standard';
  SPalAdditional='Additional';
  SPalWin32='Win32';
  SPalDialogs='Dialogs';
  SPalSystem='System';
  SPalDataControls = 'Data Controls';
  SPalDataAccess = 'Data Access';
  SPalMidas = 'Midas';
  SPalWin31 = 'Win 3.1';
  SPalActiveX='ActiveX';
  SPalDecisionCube='Decision Cube';
  SPalQReport='QReport';

// ------------------- Form captions ------------------

  SCapLines=' строк)';
  SCapGotoLineNumber='Перейти к строке';
  SCapEnterNewLine='&Введите новый номер строки:';
  SCreateOrderCaption='Порядок создания';
  STabOrderCaption='Порядок перехода';
  SCapEditing='Редактирование ';
  SCapWindowList='Список окон';
  SCapAddFields='Добавление поля';
  SCapSelectSource='Выбор источника данных';
  SCapScale='Масштабирование';
  SCapScalingFactor='&Масштаб:';
  SCapProjectManager='Менеджер проектов';
  SErrDlg  = 'Ошибка чтения формы';
  SFindText = 'Поиск текста';
  SReplText ='Замена текста';
  SPstoredEdit = 'Редактор Property Storage';
  SPackActiveX = 'Библиотеки/ActiveX';
  SNewItem = 'Новый элемент';
  SNewField = 'Новое поле';
  SFilterEdit = 'Редактор фильтра';
  SObjectExplorer = 'Проводник объектов';
  SStrlEdit = 'Редактор списка строк';

// ------------------- dcl0.pas ----------------------------

  SSaveChanges='Сохранить изменения в %s?';
  SCantUseMore='Модуль уже использует все доступные модули';
  SUseUnitCaption='Использовать модуль';

  SEmptyFileName='Имя файла не может быть пустым';
  SNotValidIdent='''%s'' не является правильным именем.';
  SOpenFileExt='Модули Дельфи |*.pas|Delphi form|*.dfm';
  SOnlyOneInstant='Может быть создан только один экземпляр TInstantReport';

// ------------------- dcfdes.pas------------------------

  SAligntoGrid =  'Выровнять по сетке' ;
  SBringToFront =  'На передний план';
  SSendToBack = 'На задний план';
  SDesAlign =  '&Выравнивание...';
  SDesSize  ='&Размер...';
  SDesScale = '&Масштаб...';
  SDesTabOrder= 'Порядок перехода...';
  SDesCreationOrder='&Порядок создания...';
  SDesViewAsText = 'Показать в виде &текста';

// ----------------- dcstring.pas ----------------------

  SVerbProperties='Свойства...';
  SInvalidTabRack='Неправильное значение';
  SReadOnlyStream='Невозможно записать в поток - только для чтения';
  SErrBlankSearch='Строка поиска не может быть пуста';
  SErrEmptySel='Попытка поиска в некорректном блоке,';
  SErrOutsideSel='Попытка поиска в отмеченном блоке , но курсор расположен вне блока';
  SErrNotFound='Строка ''%s'' не найдена';
  SAskReplace='Заменить этот текст на ''%s''?';
  SAskSaveFile=' Сохранить изменения для %s ?';

// ----------------------- dcgen.pas ------------------------------

  SErrStackEmpty = 'Стек пуст';
  SErrPackloaderExists='Загрузчик библиотек уже присутствует в проиложении';
  SErrUnknRegType='Этот тип не поддерживается функцией WriteToRegistry';

// ---------------------- dcpload.pas --------------

  SErrWithoutPackages='Загрузчик библиотек не может работать в приложении , скомпилированном без библиотек';
  SErrorPackageLoad='Ошибка при загрузке библиотеки %S';
  SOnlyOnePackageLoader='Может быть создан только один экземпляр TDCPackageLoader';
  SUnkPackageHandle='Неизвестный хандлер библиотеки' ;
  SPackAlrregist='Невозможно установить библиотеку %s,'#13#10'потому что у библиотеки %s такое же базовое имя';

// ---------------------- dcl2.pas --------------

  SErrFileNotFound='Файл %S не найден';

// ---------------------- reswrite.pas --------------

  SError        = #13#10'Код ошибки : %d';
  SErrFileOpen  = 'Невозможно открыть файл для записи';
  SErrMap       = 'Невозможно отобразить файл';
  SErrMapView   = 'Невозможно выполнить функцию MapViewOfFile';
  SErrEXE       = 'Неправильный формат файла';
  SErrNoResources  = 'Файл не содержит ресурсов';
  SErrResNotFound  = 'Ресурс не найден';

// ---------------------- dctree.pas ---------------

  SConfirmDelete = 'Удалить элемент(ы)';

// ---------------------- dcdbreg.pas --------------

  SLoadDefault = 'Загрузить параметры по умолчанию?';
  SErrNoAliasOrDriver = 'Свойства AliasName или DriverName должны быть определены';
  SVerbLoadDefault = 'Загрузить &параметры по-умолчанию?...';
  SVerbExecute = '&Выполнить';
  SVerbColumnsEditor = 'Редактор ко&лонок...';

// ---------------------- ctrlreg.pas --------------

  SVerbEditPropList='&Редактор списка свойств...';
  SVerbPropOrder='&Порядок свойств...';
  SVerbInsertObject= 'Вставить объект...';
  SVerbObjectProperties= 'Свойства объекта...';
  SVerbObjectSettings= 'Установки объекта...';
  SVerbNextFrame='&Следующий кадр';
  SVerbPreviousFrame='&Предыдущий кадр';
  SVerbNewPage='Новая страница';
  SVerbNextPage='Следующая страница';
  SVerbPreviousPage='Предыдущая страница';
  SVerbNewButton='Новая &кнопка';
  SVerbNewSeparator='Новый &разделитель';

  SVerbInputMaskEditor='Редактор маски &ввода...';
  SVerbMaskedTextEditor='&Редактор маски ...';
  SVerbImageEditor='Редактор &образа..';
  SVerbSectionsEditor='Редактор &Секций...';
  SVerbPanelsEditor='Редактор &Панелей...';
  SVerbItemsEditor='Редактор &Элементов...';
  SVerbLinesEditor = 'Редактор &Строк...';
  SVerbTabsEditor = 'Редактор &Закладок...';
  SVerbMenuDesigner='Редактор Меню...';
  SVerbBandsEditor='Редактор &Полос...';
  SVerbObjectInspector='&Инспектор объектов';

  SErrNotImplemented='Не реализовано';

// ---------------------- dcmemo.pas --------------

  SLoadColorStyles='Загрузить стили цветов';
  SSaveColorStyles='Сохранить стили цветов';
  SErrNotRGBFile='Файл не является файлом стилей цветов';


// ---------------------- dcdbtree.pas --------------

  SReplaceColumns = 'Удалить существующие колонки ?';

// ---------------------- dcedit.pas --------------

  sErrSelfLink = 'Не может быть связан сам с собой';
  sErrEmptyPopupClass = 'Не определен PopupWindowClass';
  SSelectDirectory='Выбор каталога';

// ---------------------- dcmenu.pas --------------

  sErrMultipleInstance = 'Только один экземпляр DCMenu может быть помещен на форму';
  sErrInfoAlreadySet   = 'Информация для этого пункта меню уже введена';
  sErrMainMenuImage    = 'Главные пункты меню не могут содержать образ';

// ---------------------- dcsplit.pas ---------------

  SVerbSetMinSize='Установите свойство MinSize';

// ---------------------- dcdbtree.pas ---------------

  sDatasetName='*.cds';
  sAddFields ='&Добавить поля...';
  sAddAllColumns = '&Добавить все колонки...';
  sLoadDefValues = 'Загрузить значения по умолчанию...';
  sFieldEditor='Редактор &Полей...';
  sParamEditor= 'Редактор П&араметров...';
  serrNameAlredyExists='Поле с имененем %s уже существует';

// ---------------------- dcpascal.pas ---------------

  SErrExpectedButFound = 'ожидается %s, но обнаружено %s ';
  SErrOrExpected  = 'ожидается %s или %s';
  SErrFunDefined='Функция %s уже определена';
  SErrunkn_id= 'Неизвестный идентификатор: %s';
  SErrunexp_writer= 'Неизвестный тип переменной';
  SErrunit_declared= 'Модуль %s уже определен';
  SErrbad_unit= 'Ошибка описания модуля';
  SErrfun_notfound= 'Функция %s не найдена';
  SErrlinker_error= 'Ошибка в связи';
  SErrlabel_already= 'Метка <%s> уже определена';
  SErrdeclpart= 'Ошибка в блоке описаний';
  SErrlab_notdef= 'Метка <%s> не определена';
  SErrvar_already= 'Переменная <%s> уже определена';
  SErrbad_varblock= 'Ошибка в блоке описания переменных';
  SErrvar_NotDef= 'Переменная <%s> не определена';
  SErrmeth_decerr= 'Ошибка описания метода';
  SErrbad_methparam= 'Ошибка описания параметров метода';
  SErrno_props= 'Свойства не реализованы';
  SErronly_class= 'Разрешено только описание классов';
  SErr_decl= 'Ошибка описания %s';
  SErrsynt_err='Синтаксическая ошибка в строке: %d столбце: %d'#13#10'%s';
  SErrbad_idName= 'Неправильное имя идентификатора <%s>';
  SErrbad_id= 'Неправильный идентификатор <%s>';
  SErrin_funuse= 'Неправильное использование функции';
  SErrin_procuse= 'Неправильное использование процедуры';
  SErrbad_hex= 'Ошибка описания шестнадцатиричной константы';
  SErrcompile_before= 'Необходимо откомпилировать перед запуском';
  SErrbad_realconst= 'Ошибка описания константы';
  SErrbad_charconst= 'Ошибка описания строковой константы';
  SErrunsup_partype= 'Тип параметра не поддерживается';
  SErrno_resvar= 'Переменная Result не найдена для %s';
  SErrproc_notfound= 'Процедура %s не найдена';
  SErrpar_notfound= 'Параметр %S не найден';
  SErrUnknReaderType='Неизвестный тип readerа';
  SErrInvalidParams =' Неправильное количество параметров';
  SErrInvalidType = 'Один из параметров имеет ошибочный вариантный тип';
  SErrInvalidProperty  = 'Свойство не существует или только для чтения';
  SErrInvalidCall = 'Именованные аргументы не поддерживаются';
  SErrParamNotFound = 'Параметр не найден';
  SErrTypeMismatch = 'Несоответствие типа параметра';
  SErrInvalidInterface = 'Неизвестный интерфейс';
  SErrParamOmitted = 'Требуемый параметр был пропущен';
  SErrUnknown  = 'Неизвестная ошибка';
  SErrInvCode ='Ошибочный код операции';


// ---------------------- csDelphi.pas ---------------
  SClientDataFilter = 'Файлы Client DataSet (*.cds)|*.cds|Все файлы (*.*)|*.*';
  SSaveToFile = '%Сохранить в файл...';
  SLoadFromFile = '&Загрузить из файла...';
  SClientDSAssignData = 'Связать с локальными &данными...';
// ---------------------- dcactnlst.pas ---------------

  SDefaultCategory = 'Не определена';

// ---------------------- AligUnit.pas ---------------

  SAlignmentpalette  = 'Палитра выравнивания';
  SAlignleft = 'Выровнять левые стороны';
  SAlignhor = 'Выровнять по горизонтали';
  SCenterHor = 'Центрировать по горизонтали в окне';
  SSpaceeqHor ='Равномерно разместить по горизонтали';
  SAlignright = 'Выровнять правые стороны';
  SAligntops = 'Выровнять верхние стороны';
  SAlignvert = 'Выровнять по вертикали';
  SCentervert = 'Центрировать по вертикали в окне';
  SSpaceeqVert = 'Равномерно разместить по вертикали';
  SAlignbottom = 'Выровнять нижние стороны';
  SVerbStayOnTop = '&Поверх всех окон';
  SVerbHide = '&Спрятать';

// ---------------------- DAlign.pas ---------------

  SAlignment  = 'Выравнивание';
  SHorizontal = ' Горизонтальное';
  SVertical = ' Вертикальное';
  SHorizontalAlignment = 'Без изменений'#13#10'Левые стороны'#13#10'Центры'#13#10+
                  'Правые стороны'#13#10'Равномерно'#13#10'По - центру';
  SVerticalAlignment = 'Без изменений'#13#10'Верхние стороны'#13#10'Центры'#13#10+
                      'Нижние стороны'#13#10'Равномерно'#13#10'По - центру';

// ---------------------- DcImgEd.pas ---------------

  SAskSeparateBitmaps= 'Размерность Bitmap для %s больше размерности Imagelist. Разделить на %d отдельных bitmap ?';
  SVerbImageListEditor='Редактор &ImageList...';
  SSelImage = '&Выбранный образ';
  STransColor = '&Прозрачный цвет';
  SFillColor = '&Цвет заполнения';
  SOptions = 'Опции';
  SCrop = 'Без изменений';
  SStretch = 'Растяжение';
  SCenter = 'По центру';
  SApply = 'При&менить';
  SAddImage = '&Добавить';
  SDelete = 'Удал&ить';
  SClear = '&Очистить';

// ---------------------- DcPalFrm.pas ---------------

  SComPal = 'Палитра компонент';

// ---------------------- dcstrled.pas ---------------

  SOpen = 'Открыть';
  SCodeEdit = '&Редактор кода...';

// ---------------------- dsize.pas ---------------

  SSize  =  'Размер';
  SWidth =  ' Ширина';
  SHeight = ' Высота';
  SHorizontalSize ='Без изменений'#13#10'К наименьшему'#13#10'К наибольшему'#13#10'Ширина:';
  SVerticalSize = 'Без изменений'#13#10'К наименьшему'#13#10'К наибольшему'#13#10'Высота:';

// ---------------------- glyphed.pas ---------------

  SCopy = 'Копировать';
  SPaste = 'Вставить';

// ---------------------- inspunit.pas ---------------

  SInspectorTabs = 'Свойства'#13#10'События';
  SVerbShowCategory = 'Показать категории';
  SVerbDelphiStyle = 'Стиль Delphi';
  SVerbVBStyle =  'Стиль Visual Basic';

// ----------------------MaskPr.pas ---------------

  SInputMask = 'Маска &ввода';
  SCharBlank = 'Пустой символ';
  SSaveLiterChar = 'Сохранять прописные';
  STestInput = '&Тест';
  SMask = '&Маски...';

// ----------------------MskText.pas ---------------

  SInputText = '&Ввод текста';
  SEditMask = 'Редактор маски';

// ----------------------newfield.pas ---------------

  SFieldName = '&Имя';
  SFieldType = '&Тип';

// ----------------------packcfg.pas ---------------

  SAddPack = 'Добавить библиотеку/Зарегистрировать ActiveX';
  SRemovePack = 'Удалить библиотеку';
  SShowComp = 'Показать компоненты';

// ----------------------pstored.pas ---------------

  SSelectAll ='&Выбрать все';
  SUnselectAll = '&Отменить выбор';

// ----------------------replunit.pas ---------------

  STextToFind = '&Искать текст:';
  SReplaceWith = '&Заменить на:';
  SCaseSensitive = '&Учитывать регистр';
  SWholeWord = '&Только целые слова';
  SRegExpr = '&Регулярные выражения';
  SPropmtRepl = '&Подсказка при замене';
  SDirection = 'Направление';
  SForward = '&Вперед';
  SBackward = '&Назад';
  SScope = 'Диапазон';
  SGlobal = '&Глобальный';
  SSelText = 'Выбранный текст';
  SOrigin = 'Начинать';
  SFromCursor = 'С позиции &курсора';
  SEntireScope = 'С н&ачала';
  SReplAll = 'Заменить все';

// ----------------------rerdlg.pas ---------------

  SErrMess = '%s.  Игнорировать ошибку и продолжить?  Замечание: Игнорирование ошибки'+
                  ' может вызвать удаление компоненты или потерю значений свойств.';
  SIgnoreAll = 'Игнор. &все';

// ----------------------Searunit.pas ---------------

  SFind = 'Найти';

// ----------------------TreeEd.pas ---------------

  SRefresh = 'Обновить';
  SLevelUp = 'Вверх на один уровень';
  SAddItem = 'Добавить элемент';
  SAddSubItem = 'Добавить подуровень';
  SDeleteItem = 'Удалить элемент';
  SLargeIcon =  '&Большие значки';
  SSmalIcon  = '&Мелкие значки';
  SListStyle = '&Список';
  SReportStyle = '&Таблица';

// ----------------------MainUnit.pas -------------------------

  SFileMenu = '&Файл';
  SFileNewMenu = '&Новый...';
  SFileNewAppMenu = 'Новое &Приложение';
  SFileNewFormMenu = 'Новая &Форма';
  SFileNewDataModuleMenu = 'Новый &Модуль Данных';
  SFileOpenMenu = '&Открыть...';
  SFileOpenWorkspaceMenu = 'Открыть &Рабочую Область...';
  SFileSaveWorkspaceMenu = 'Сохранить Рабочую Область';
  SFileSaveWorkSpaceAsMenu = 'Сохранить Рабочую Область как...';
  SFileSaveAllMenu = 'Сохранить &Все';
  SFileExportToMenu = 'Э&кспорт в...';
  SFileCloseAllMenu = '&Закрыть Все';
  SFileUseObjectMenu = '&Использовать объект...';
  SFileAddtoprojectMenu = '&Добавить к проекту...';
  SFileRecentFilesMenu = '&Недавние файлы';
  SFileRecentWorkSpacesMenu = 'Недавние Рабочие Области';
  SFilePrintMenu = '&Печать...';
  SFileExitMenu = 'Вы&ход';
  SEditMenu = '&Правка';
  SEditUndoMenu = '&Отменить';
  SEditRedoMenu = '&Повторить';
  SEditCutMenu = 'В&ырезать';
  SEditCopyMenu = '&Копировать';
  SEditPasteMenu = '&Вставить';
  SEditLockControlsMenu = 'Запретить перемещение';
  SSearchMenu = '&Поиск';
  SSearchFindMenu = '&Найти...';
  SFindinFilesMenu = 'Найти в файлах...';
  SSearchReplaceMenu = '&Заменить...';
  SSearchSearchAgainMenu = 'По&вторить поиск';
  SIncrementalSearchMenu = 'Последовательный поиск';
  SSearchGotoLineMenu = 'Перейти к &строке ...';
  SViewMenu = '&Вид';
  SViewProjectManagerMenu = 'Менеджер &проектов';
  SViewAlignmentPaletteMenu = 'Палитра &выравнивания';
  SViewToggleFormUnitMenu = 'Поменять форму/модуль';
  SViewWindowListMenu = 'Список &Окон...';
  SViewNewEditWindowMenu = 'Новое Окно &Редактора';
  SViewClipboardHistoryMenu = '&Буфер обмена';
  SViewPackagesMenu = 'Библиотеки/ActiveX';
  SRunMenu = 'Запуск';
  SRunQuickRunMenu = '&Внешний запуск';
  SRunParametersMenu = '&Параметры...';
  SRunProgramResetMenu = '&Остановка программы';
  SEvaluateModifyMenu = 'Вычислить/поменять';
  SToolsMenuMenu = '&Инструменты';
  SToolsOptionsItemMenu = '&Настройки...';
  SIDEInspectorMenu = 'I&DE Инспектор';
  SHelpMenu = 'По&мощь';
  SHelpContentsMenu = '&Содержание...';
  SHelpHomePageMenu = '&Домашняя страница';
  SHelpWritetousMenu = '&Напишите нам';
  SHelpOnlineregMenu = '&Регистрация';
  SHelpAboutMenu = '&О программе...';
  SPopupComponentsMenu = '&Компоненты...';

// ----------------------OptUnit.pas -------------------------

  SPreferences = 'Предпочтения';
  SVbStyle = 'Стиль VB';
  SDelphiStyle = 'Стиль Delphi';
  SShowCategory = 'Категории';
  SOInspector = 'Инспектор объектов';
  SSmartPopup = 'Умный popup';
  SEditAliases = 'Алиасы';
  SFormDesigner = 'Дизайнер форм:';
  SGridStepX = 'Шаг сетки по &X';
  SGridStepY = 'Шаг сетки по &Y';
  SDisplayGrid = 'Отображать &сетку';
  SSnapToGrid  = 'Выравнивать по сетке';
  SShowCaptions = '&Названия компонент';
  SEditor = 'Редактор';
  STabStops = '&Позиции Tab:';
  SBlockIndent = 'Отступ:';
  SKeyMappings = 'Раскладка';
  SEditorOptions = '&Опции редактора:';
  SAutoIndentMode= '&Авто отступы';
  SSmartTab = 'Умный tab';
  SBackUnindents = '&Удаление отcтупов по <-';
  SShowLineNumbers = '&Номера строк';
  SShowLineNumbersOnGutter = 'Нумерация на полосе редактора';
  SGroupUndo = '&Групповая отмена';
  SCursorBeyondEof = 'Курсор за концом файла';
  SPersistentBlocks = 'Постоянные блоки';
  SOverwriteBlocks = 'Перезаписывать блоки';
  SDblClickLine = '&Dblclick-выбор строки';
  SFindTextAtCursor = 'Поиск текста от курсора';
  SCutCopyEnabled = '&Удаление и копирование';
  SSyntaxHighlighting = 'Подсветка синтаксиса';

  SCursorByondEol  = '&Cursor beyond EOL';
  SSelectionByondEol = '&Selection beyond EOL';
  SOverCaretBlock   = '&Overwrite cursor as block';
  SDisableDrag  = 'D&isable dragging';

  SDisplay = 'Вид';
  SEditFont  = '&Шрифт:';
  SOptionSize =  '&Размер:';
  SEditMargin = 'Граница редактора:';
  SColor  = '&Цвет:';
  SColor2  = 'Цв&ет:';
  SStyle  = '&Стиль:';
  SStyle2  = 'Сти&ль:';
  SOptionWidth = 'Ш&ирина:';
  SOptionWidth2 = 'Шири&на:';
  SPosition= '&Позиция:';
  SVisible = '&Видимая';
  SVisible2 = 'Ви&димая';
  SEditGutter = 'П&олоса редактора:';
  sEditorColor = 'Цве&т редактора:';
  SColors = 'Цвета';
  SElements = '&Элемент:';
  SBackColor = 'Цвет &фона:';
  SForeColor = '&Цвет изображения:';

  SBoldFont = '&Bold';
  SItalicFont = '&Italic';
  SUnderLineFont = '&Underline';

  SUsedefaults = 'По умолчанию для:';
  SForeground = '&Изображения';
  SBackground = 'Ф&она';

  SProperties = 'Свойства';
  SOkButton = 'Ok';
  SCancelButton = 'Отмена';
  SHelpButton = '&Справка';

  SInspectOptions = 'Инспектор';
  SDesignerOptions = 'Дизайнер';

//----------------diffmake.pas------------------------

  SErrCRC='Ошибка CRC';
  SErrSmallBuffer='Размер буфера должен быть не менее 4 байт';

//------------formfill.pas---------------------------

  SErrFillTypeStarted = 'Заполнение уже запущено';

//------------editunit.pas---------------------------

  SOpenFileatCursor = 'Открыть &файл у позиции курсора ';
  SBrowseSymbolatCursor = 'Просмотреть &символ у позиции курсора ';
  STopicSearch = 'Поиск &темы';
  SToggleBreakpoint = 'Установить точку &останова';
  SRuntoCursor  =  '&Выполнить до курсора';
  SAddWatchatCursor =  '&Добавить просмотр у позиции курсора ...';
  SViewasForm = 'Просмотреть как форму';
  SReadOnly =  'Только для &чтения';
  SClosePage = '&Закрыть старницу';
  SMessageView =  'Просмотр сообщений';

//new
//---------dcmenu.pas--------------------------------------
  sErrNotAForm = 'DCMenu can be placed only into the form';

//---------dcpascal.pas--------------------------------------

  SErrMisplacedBreak = 'Break outside of loop';
  SErrMisplacedContinue = 'Continue outside of loop';

//---------dcstdctl.pas--------------------------------------

  SErrCircularReference='Circular reference';

//---------dtreeed.pas--------------------------------------

  SNewNode = 'New Node';

//------------- Info Tree constants -------------------------

  SErrReferencedObject='Объект ссылается на другие обекты';

  SErrEmptyLink = '%s: Связъ не определена';
  SIUnknownNotSupported   = 'IUnknown не поддерживается';
  SIDCRowSetNotSupported  = 'IDCRowSet не поддерживается';
  SErrActiveObject = 'Объект активный. Пожалуйста закройте его';
  SErrNonActiveInfoSet = 'InfoSet не активный. Пожалуйста откройте его';
  SErrUnsupportedDataType = 'Поле "%s" имеет неподдерживаемій тип данних';
  SErrSetInfoSet='Пожалуйста установите свойство InfoSet';
  SErrFieldReadOnly='Поле "%s" доступно только для чтения';
  SErrFieldDestroyed='Поле "%s" удалено';
  SErrHandlerAlreadyExists='Обработчик уже существует';
  SErrHandlerNotExists='Обработчик не существует';
  SErrObjectIsNull='Объект равен NULL';
  SIDCMasterInfoSetNotSupported = 'IDCMasterInfoSet не поддерживается';
  SErrInsert = 'Немогу вставить узел';
  SErrChangesNotSupported = 'Infoset не поддерживает изменения';

  //ReliInfoSet messages
  SErrFieldNotFound='Поля "%s" не найдены.';

  SErrSetReliItem='Пожалуйста установите свойство %s';
  SErrCMastAndDetDifferent='Номера полей Detail и Master несоответствуют';
  SErrRelFieldNotFound='Поля "%s" не найдены.';
  SErrEmptyDisplayField='DisplayName пустое';
  SErrIncompatibleDataType='Тип данных master "%s" и detail "%s" несовместимые';

  SErrSetReliItemIndex='Пожалуйста установите свойство %s . Ошибка в элементе с номером %d';
  SErrCMastAndDetDifferentIndex='Номера полей Detail и Master несоответствуют. Ошибка в элементе с номером %d';
  SErrRelFieldNotFoundIndex='Поля "%s" не найдены. Ошибка в элементе с номером %d';
  SErrEmptyDisplayFieldIndex='DisplayName пустое. Ошибка в элементе с номером %d';
  SErrIncompatibleDataTypeIndex='Тип данных master "%s" и detail "%s" несовместимые. Ошибка в элементе с номером %d';

  SErrInvalidFilter = 'Неправельно сформирован фильтр выражений';
  SErrInvalidFieldType = 'Неверний тип поля';
  SErrSetDataSet='%s: Пожалуйста установите свойство DataSet';
  SErrSetRootDataSet='%s: Пожалуйста установите свойство RootDataSet';
  SErrNotInfoSetDataSet='Значение должно быть типа TDataSet или InfoSet';

  //InfoDB constants
  SErrUniqueFieldAlreadyRegistered='Уникальное поле уже зарегистрировано';
  SErrUniqueFieldIsNotRegistered='Для этого DataSet уникальное поле не зарегистрировано';
  SErrInvalidBookmark='Неверний bookmark';

  //Memo print messages
  SFileNameUnknown='<Неизвесный>';
  SFileSelectedBlock='<Выделеный блок>';
  SPrintingPage='Печать страницы %d из %s';
  SPageCaption='Страница %d/%d';
  SMultiDot=' ... ';
  SPrintingOnPrinter='Печать на принтер %s';

  //Print progress messages
  SPrintStatus='Статус печати';
  SSearchPrinters='Поиск принтеров ...';
  SPrintProgress='Печать страниц:    подготовка ...';

  //Print Dialog messages
  SPrintFormCaption='Печать';
  SPrintFormCaptionSelection='Выбор печати';
  SPrintDestCaption='Файл для печати:';
  SPrintSelectedBlock='&Печать выделеного блока';
  SOptionsCaption='Опции:';
  SSetupButton='&Установка...';
  SHeaderPage='Заголовок/номера &страниц';
  SLineNumber='&Номера страниц';
  SSyntaxPrint='&Печать синтаксиса';
  SUseColor='&Цветная печать';
  SShowPrintProgress='Показывать &статус печати';
  SWrapLines='&Перенос с&трок';
  SLeftMargin='Левое &выравнивание:';

  SErrScriptLanguageNotSpecified = 'Язык скрипта не определен';

  //TSyntaxScheme
  SCantReadSSchemeFrom = 'Невозможно считать схему из ';
  SFromFile = 'файла';
  SFromStream = 'потока';

  //TSyntaxScheme Editor section
  SSSETitle = 'Редактор TSyntaxScheme';
  SSchemeName = '&Название Схемы:';
  SBlocks = '&Блоки';
  SExtensions = '&Расширения';
  SLoad = 'Загрузить';
  SSave = 'Сохранить';
  SLoad1 = '&Загрузить';
  SSave1 = '&Сохранить';
  SSaveAs = 'Сохранить как';
  SClear0 = 'Очистить';
  SApply0 = 'Применить';
  SBlkDelimiters = '&Ограничители Блоков:';
  SBlkOptions = 'Опции Блоков:';
  SCaseSens = 'Различать &Регистр';
  SUseMeta = 'Исп. &Метасимвол';
  SMetaEscape = 'для &Esc-символов';
  SMetaWrapLines = 'для &Длинных Строк';
  SStyleText = 'Обычный &Текст:';
  SUseSymbols = 'Выделять &Символы';
  SPageCommon = 'Общие';
  SPageComments = 'Комментарии';
  SPageFullLine = 'Полнострочные';
  SPageStrings = 'Строки';
  SPageNumbers = 'Числа';
  SPageIdents = 'Идентификаторы';
  SPageKeywords = 'Ключ. Слова';
  SPagePopups = 'Диалоги';
  SAdd = 'Добавить';
  SRemove = 'Удалить';
  SEdit = 'Редактировать';
  SAdd1 = '&Добавить';
  SRemove1 = '&Удалить';
  SEdit1 = '&Редактировать';
  SAdd2 = 'Д&обавить';
  SRemove2 = 'Уд&алить';
  SEdit2 = 'Р&едактировать';
  SStyleButton = 'Стиль...';
  SUseComments = 'Выделять &Комментарии';
  SUseCommentsSL = '&Однострочные';
  SUseCommentsML = '&Многострочные';
  SUseCommentsFL = '&Полнострочные Комментарии';
  SUseDirectives = 'Выделять &Директивы';
  SUseStrings = 'Выделять &Строки';
  SUseStringsSL = '&Однострочные';
  SUseStringsML = '&Многострочные';
  SUseNumbers = 'Выделять &Числа';
  SIntNum = '&Целые:';
  SFloatNum = '&Веществен-'#13'ные:';
  SHexNum = '&Шестнадца-'#13'тиричные:';
  SPSNumbers = ' Особые: ';
  SWithPrefix = 'с &префиксом';
  SWithSuffix = 'с &суффиксом';
  SWithPS = 'с преф. &и суфф.';
  SWithPrefixes = 'с п&рефиксами';
  SWithSuffixes = 'с с&уффиксами';
  SWithPSs = 'с пре&ф. и суфф.';
  SMultiSuffixes = 'исп. &множественные';
  SPSComposition = 'исп. &сочетание П && С';
  SUseIdentifiers = 'Выделять &Идентификаторы';
  SSpecIdents = 'Особые Идентифика-'#13'торы && Ключ. Слова:';
  SUseKeywords = 'Выделять &Ключ. Слова:';
  SKWSets = ' Наборы: ';
  SCurKWSets = ' Текущий набор: ';
  SFontName = '&Имя шрифта:';
  SFontSize = '&Размер шрифта:';
  SFontColor = '&Цвет шрифта:';
  SFontStyles = 'Стиль шрифта:';
  SBackColor1 = 'Цвет &фона:';
  SBold = '&Жирный';
  SItalic = '&Наклонный';
  SUnderline = '&Подчеркнутый';
  SStrikeout = '&Зачеркнутый';
  SUseDefFont = 'Исп. шрифт по умолч.';
  SUseDefBack = 'Исп. фон по умолчанию';
  SArePartOfBlock = ' являются &частью блока';
  SSelectBlock = '&Выберите блок:';
  SFilterScheme = 'Файлы синтакс. схем (*.sch)|*.sch|Все файлы (*.*)|*.*';
  SFilterKeywords = 'Текстовые файлы (*.txt)|*.txt|Все файлы (*.*)|*.*';
  SCaptionSet = 'Набор:';
  SCaptionKeyword = '&Ключ. Слово:';
  SCaptionDelimiter = '&Ограничитель:';
  SCaptionLeftDlmtr = '&Левый Ограничитель:';
  SCaptionRightDlmtr = '&Правый Ограничитель:';
  SCaptionPrefix = 'Префикс:';
  SCaptionSuffix = 'Суффикс:';
  SCaptionBlock = 'Блок:';
  SCaptionParent = '&Родитель:';
  SCaptionExt = '&Расширение:';
  SQueryRemoveBlock = 'Вы действительно хотите удалить блок';
  SQueryRemoveKWSet = 'Вы действительно хотите удалить набор';
  SAnd = ' и ';

//=================== UNTRANSLATED SECTION ===================
{------------ This section will be translated ---------------}
//================= END UNTRANSLATED SECTION =================

